[package]
name = "feff-core"
version.workspace = true
edition.workspace = true

[dependencies]
globset.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
